---
booktitle: Proceedings of The 28th Conference on Learning Theory
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 40
year: '2015'
shortname: COLT
start: 2015-07-03
end: 2015-07-06
published: 2015-06-26
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open
  title: Open Problems
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: COLT-2015
month: 0
cycles: false
editor:
- given: Peter
  family: Grünwald
- given: Elad
  family: Hazan
- given: Satyen
  family: Kale
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 28th Conference on Learning Theory
    Held in Paris, France on 03-06 July 2015

  Published as Volume 40 by the Proceedings of Machine Learning Research on 26 June 2015.

  Volume Edited by:
    Peter Grünwald
    Elad Hazan
    Satyen Kale

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 03--06 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v40"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v40
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: http://www.learningtheory.org/colt2015/
  location: Paris, France
  dates:
  - 2015-07-03
  - 2015-07-04
  - 2015-07-05
  - 2015-07-06
  number: 28
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
